import { arrayOf, boolean, object, oneOf, optional, string } from './ext-shared.js'

const quotedTweet = object({
  quotedBy: string({ maxLength: 50 }),
  user: string({ maxLength: 30 }),
  time: string({ maxLength: 30 }),
  text: optional(string({ maxLength: 280 })),
})

/**
 * @type {Record<import('./types').UserSettingsKey, import('./ext-shared').FieldDescriptor>}>}
 */
const v5 = {
  // Shared
  addAddMutedWordMenuItem: boolean(),
  addFocusedTweetAccountLocation: boolean(),
  bypassAgeVerification: boolean(),
  darkModeTheme: oneOf(['dim', 'lightsOut']),
  defaultFollowingToRecent: boolean(),
  defaultToFollowing: boolean(),
  defaultToLatestSearch: boolean(),
  disableHomeTimeline: boolean(),
  disableTweetTextFormatting: boolean(),
  disabledHomeTimelineRedirect: oneOf(['notifications', 'messages']),
  dontUseChirpFont: boolean(),
  dropdownMenuFontWeight: boolean(),
  fastBlock: boolean(),
  followButtonStyle: oneOf(['monochrome', 'themed']),
  hideAdsNav: boolean(),
  hideBookmarkButton: boolean(),
  hideBookmarkMetrics: boolean(),
  hideBookmarksNav: boolean(),
  hideBusinessNav: boolean(),
  hideChatNav: boolean(),
  hideCommunitiesNav: boolean(),
  hideComposeTweet: boolean(),
  hideConnectNav: boolean(),
  hideCreatorStudioNav: boolean(),
  hideDiscoverSuggestions: boolean(),
  hideEditImage: boolean(),
  hideExplorePageContents: boolean(),
  hideFollowingMenu: boolean(),
  hideFollowingMetrics: boolean(),
  hideForYouTimeline: boolean(),
  hideGrokNav: boolean(),
  hideGrokTweets: boolean(),
  hideInlinePrompts: boolean(),
  hideJobsNav: boolean(),
  hideLikeMetrics: boolean(),
  hideListRetweets: boolean(),
  hideListsNav: boolean(),
  hideMetrics: boolean(),
  hideNotificationLikes: boolean(),
  hideNotificationRetweets: boolean(),
  hideNotifications: oneOf(['ignore', 'badges', 'hide']),
  hidePremiumReplies: boolean(),
  hidePremiumUpsells: boolean(),
  hideProfileHeaderMetrics: boolean(),
  hideProfileRetweets: boolean(),
  hideQuoteTweetMetrics: boolean(),
  hideQuotesFrom: arrayOf(string({ maxLength: 50 }), { maxLength: 10000 }),
  hideReplyMetrics: boolean(),
  hideRetweetMetrics: boolean(),
  hideSeeNewTweets: boolean(),
  hideShareTweetButton: boolean(),
  hideSortRepliesMenu: boolean(),
  hideSpacesNav: boolean(),
  hideSubscriptions: boolean(),
  hideSuggestedContentSearch: boolean(),
  hideSuggestedContentTimeline: boolean(),
  hideTweetAnalyticsLinks: boolean(),
  hideUnavailableQuoteTweets: boolean(),
  hideVerifiedTabs: boolean(),
  hideViewActivityLinks: boolean(),
  hideViews: boolean(),
  mutableQuoteTweets: boolean(),
  mutedQuotes: arrayOf(quotedTweet, { maxLength: 10000 }),
  premiumBlueChecks: oneOf(['ignore', 'replace', 'hide']),
  quoteTweets: oneOf(['separate', 'hide', 'ignore']),
  redirectChatNav: boolean(),
  redirectToTwitter: boolean(),
  reducedInteractionMode: boolean(),
  restoreLinkHeadlines: boolean(),
  restoreOtherInteractionLinks: boolean(),
  restoreQuoteTweetsLink: boolean(),
  restoreTweetSource: boolean(),
  retweets: oneOf(['separate', 'hide', 'ignore']),
  revertXBranding: boolean(),
  showBookmarkButtonUnderFocusedTweets: boolean(),
  showPremiumReplyBusiness: boolean(),
  showPremiumReplyFollowedBy: boolean(),
  showPremiumReplyFollowersCount: boolean(),
  showPremiumReplyFollowersCountAmount: oneOf(['1000', '10000', '100000', '1000000']),
  showPremiumReplyFollowing: boolean(),
  showPremiumReplyGovernment: boolean(),
  sortReplies: oneOf(['relevant', 'recent', 'liked']),
  tweakQuoteTweetsPage: boolean(),
  unblurSensitiveContent: boolean(),
  uninvertFollowButtons: boolean(),
  // Desktop only
  addUserHoverCardAccountLocation: boolean(),
  fullWidthContent: boolean(),
  fullWidthMedia: boolean(),
  hideAccountSwitcher: boolean(),
  hideExploreNav: boolean(),
  hideExploreNavWithSidebar: boolean(),
  hideLiveBroadcasts: boolean(),
  hideMessagesDrawer: boolean(),
  hideSidebarContent: boolean(),
  hideSuggestedFollows: boolean(),
  hideTimelineTweetBox: boolean(),
  hideTodaysNews: boolean(),
  hideWhatsHappening: boolean(),
  navBaseFontSize: boolean(),
  navDensity: oneOf(['default', 'comfortable', 'compact']),
  showRelevantPeople: boolean(),
  // Mobile only
  hideLiveBroadcastBar: boolean(),
  hideMessagesBottomNavItem: boolean(),
  preventNextVideoAutoplay: boolean(),
  // Experiments
  customCss: string({ maxLength: 50000 }),
  hideToggleNavigation: boolean(),
  tweakNewLayout: boolean(),
}

/** @type {import('./ext-shared').SettingsSchemas} */
export const schemas = [
  ['5.0.0', v5],
]

export const currentSettingsSchema = schemas.at(-1)[1]