name: "submit"
on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          archive: "web-ext-artifacts/tweak_new_twitter-{version}.zip"
          keys: ${{ secrets.SUBMIT_KEYS }}
